name: Build to Itch.io
run-name: ${{ github.actor }} is building to Itch.io 🚀

on: [push]

env:
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}


jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip
          mv Godot_v4.2.2-stable_linux.x86_64 ~/.local/bin/godot
          godot --version
      
      - name: Build Godot project
        run: godot --export-release "HTML5" Lem_Jam.zip

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Upload to Itch.io using Butler
        run: |
          ./butler login
          ./butler push Lem_Jam.zip salach-malejkum/lem-jam:html5
